### ISSUE TITLE
Allow defining new Tex macros

### ISSUE THREAD

**Issue by darcamo** [Galadirith/markdown-preview-plus#11]
Mathjax allow us to define new tex macros so that we can use them in equations, but I couldn't find a way to configure this in MPP. Since my equations often have some macros I have defined they don't work correctly in MPP.

To generate the final html I use pandoc with the "-A filename" option to append my config file to the final html, which works great. The content of this config file is something like

```
<script type="text/x-mathjax-config">
MathJax.Hub.Register.StartupHook("TeX Jax Ready",function () {
  var TEX = MathJax.InputJax.TeX;

  // New Operator
  TEX.Macro("rank","\\operatorname{rank}");
  
  // Many other TEX.Macro statements
  
});
</script>
```

Loading this file in MPP would be great, but any way to define new TEX macros would be enough for me.

**Comment by Galadirith** [comment]
@darcamo Thanks for the suggestion, that should absolutely be possible. Im thinking that probably the best way to do this would to have a user script much like yours that is run once MathJax has been loaded in Atom. That way you could define Macros or call any other methods in the MathJax API.

As a workaround until I get some time to implement this there are ways you can get macros working in MPP. The first is to us the `\def` command inside a maths block. You can find more details [here](http://docs.mathjax.org/en/latest/tex.html#defining-tex-macros) but a functional way to to this might be to prepend or append to your .md file with a single maths block with all you macros in it, something like
````latex
$$
\def\<macro-one-name>{<macro-one-body>}
\def\<macro-two-name>{<macro-two-body>}
...
$$
````

That of course isn't ideal if you have lots of macro's you use regularly and clutters up the .md file. A more hacky workaround is to add something like the following to your `init` script (you can open that up by **File &rsaquo; Open Your Init Script**)
````javascript
setTimeout () ->
  MathJax.Hub.Register.StartupHook "TeX Jax Ready", () ->
    MathJax.InputJax.TeX.Definitions.Add
      macros:
        <macro-one-name>: ["Macro", "<macro-one-body>"],
        <macro-two-name>: ["Macro", "<macro-two-body>"],
        ...
    return
  return
, 5000
````
or if your init script is pure javascript rather than coffescript you can use something like
````javascript
setTimeout(function(){
  MathJax.Hub.Register.StartupHook("TeX Jax Ready", function () {
    MathJax.InputJax.TeX.Definitions.Add({
      macros: {
        <macro-one-name>: ["Macro", "<macro-one-body>"],
        <macro-two-name>: ["Macro", "<macro-two-body>"],
        ...
      }
    });
  });
}, 5000)
````
You can find more details on `MathJax.InputJax.TeX.Definitions.Add`, and using arguments [here](http://docs.mathjax.org/en/latest/extension-writing.html#extension-to-define-tex-macros). The `setTimeout` is needed because the `init` script loads before MathJax has been loaded by MPP so `MathJax` isn't define by the time `init` loads, but 5s should be more than long enough to wait. A bit of a hack but more convenient I think.

(sorry I did use your `MathJax.InputJax.TeX.Macro` method way. I couldn't understand how to use the `MathJax.InputJax.TeX.Macro` method as I couldn't find any docs on it, and looking at the [code](https://github.com/mathjax/MathJax/blob/a4b82c521efc0f1845533bb85c7e41477fd67c42/unpacked/jax/input/TeX/jax.js#L1588) briefly was no help)

I hope that helps @darcamo, please let me know if you have questions regarding any of the stuff above, or anything else. I'll get round to implementing this properly as soon as I can :D

**Comment by darcamo** [comment]
I don't have anything in my init.coffee file. I started using atom only recently since I need a good editor for markdown with latex preview.

**Comment by Galadirith** [comment]
@darcamo oh I'm sorry my question was ambiguous. You said

> I tried adding the code below anyway, but it didn't have any effect

What I meant was could you send me your `init.coffee` file including the exact code that you said you added; even a missplaced space could make a difference.

(Just to make sure my original code wasn't unclear the `, ...` is simply a placeholder for further macros, and shouldn't literally be added to `init.coffee`. So for example if you wanted to define just two macro's you would add the following
````javascript
setTimeout () ->
  MathJax.Hub.Register.StartupHook "TeX Jax Ready", () ->
    MathJax.InputJax.TeX.Definitions.Add
      macros:
        vtH: ["Macro", "\\mathbf{h}"],
        mtH: ["Macro", "\\mathbf{h}"]
    return
  return
, 5000
````
)

**Comment by darcamo** [comment]
Thanks for your help @Galadirith.

The "..." was the problem. Now it works correctly.

**Comment by cben** [comment]
FWIW, `$\newcommand{...}{...}$` works too.
MathJax supports all the common macro-defining syntaxes, as long as it gets to see them; wrapping in $...$ achieves that.

But in real .tex syntax using commands such as `\newcommand` in math mode is (AFAIK) an error, so it'd be nice to recognize them without dollars.  Both MathJax and pandoc support that.  If you want to support it in your markdown parser, the tricky part is knowing where exactly it ends.  I my own project I took the easy heuristic they end at end-of-line, which works but only if users knows that's the rule...

**Comment by Galadirith** [comment]
@cben Thanks for the info. Which is the project you are talking about, I would love the checkout out your code :D

> Both MathJax and pandoc support that.

I didn't know MathJax supported that actually. The docs suggest that macro definitions have to be [enclosed in maths delimiters](http://docs.mathjax.org/en/latest/tex.html#defining-tex-macros) also but then I haven't actually tested it myself.

@KCErb has implemented persistent macro support that loads macros from a file in Galadirith/markdown-preview-plus#14 which will be merged in soon which will be another great way to get macros working.

Thanks again @cben :D

**Comment by cben** [comment]
Oops, you're right.  MathJax recognizes a few syntaxes without math delimiters (`\begin...\end`, `\eqref`), but not  macro definitions (just tested to confirm, and I said so myself in my first paragragh) 

I do think since syntaxes such `$\newcommand...$` are not legal in LaTeX, it'd be more intuitive not to require delimiters in markdown.  But I don't care now that the pandoc conversion landed :-)

"My project" is a markdown editor with in-place math rendering (and real-time collaboration).  Example:
https://mathdown.net/?doc=demo#Welcome-to-binom-mathcal-Math-text-down-abc
(see "# Macros" section, put cursor after "bar" and press left arrow - you'll see the `$\foo$` source)
The math recognition is "implemented" with this messy regexp (now I have 2 problems):
https://github.com/cben/CodeMirror-MathJax/blob/2e5a9fa5f77f800eb3cb9048167dee96a00ce39b/render-math.js#L264
the relevant part being `\\(?:re)?newcommand\{.*\}` -- greedy till last } on the line -- which works well in practice, but only if people don't try multi-line macro definitions.
Knowing where multi-line macros end would have to at least count nested braces; pandoc pulls it off because it actually understand the macro definition syntax and expands them. 
[That project hadles the math-inside-CodeMirror; the rest is at https://github.com/cben/mathdown]

**Comment by Galadirith** [comment]
Thanks @cben thats some awesome stuff. Yeh I completely agree that would be more intuitive. Coming from a science background I personally want any extended markdown syntax supporting a LaTeX to be as close to the LaTeX syntax as possible ... but I don't want to guide us into that discussion ;D

Definitely with @leipert fantastic work on adding Pandoc support anyone can now live the dream :D Thanks again @cben.

**Comment by Galadirith** [comment]
@leipert is there anything further to do for this issue? This issue was sort of an amalgamation of general comments on macro support without one specific question. As far as the title goes `Allow defining new TeX macros` I think we've hit that with #75.

If there are more specific request then it would be easier to spin them off to individual issue, otherwise I'm happy to close this now.
