### ISSUE TITLE
Automatically open up preview pane when opening .md file

### ISSUE THREAD

**Issue by mmoh** [Galadirith/markdown-preview-plus#127]
The default markdown package does this. Would be useful to have this as an option.

**Comment by Galadirith** [comment]
Thanks @mmoh. Do you have [`markdown-preview-opener`](https://atom.io/packages/markdown-preview-opener). I ask because I wasn't aware that the default [`markdown-preview`](https://atom.io/packages/markdown-preview) package had this feature built it. There is in fact a fork [`markdown-preview-plus-opener`](https://atom.io/packages/markdown-preview-plus-opener) that I believe does exactly what your asking for. Please let me know if that package does what you need, thanks @mmoh.

**Comment by mmoh** [comment]
Great that package works ` markdown-preview-plus-opener`! Thanks.
