### ISSUE TITLE
Unhelpful error message on citeproc citation not found

### ISSUE THREAD

**Issue by happydemic** [Galadirith/markdown-preview-plus#128]
Thanks for this excellent tool. I particularly appreciate the fact that you can preview citations.

One small enhancement request: when a pandoc citation is missing from the specified .bib file, Markdown-Preview-Plus crashes with the error 'Pandoc Error:
pandoc exited with code 1: pandoc: [object Object]: openFile: does not exist (No such file or directory)'. 

When running the same file through pandoc, the file parses fine and pandoc includes a 'citation not found' placeholder in the output by the broken citation.

Is there any chance that Markdown Preview Plus could either: do something similar; or: identify the broken citation which threw the error? 

In a long document with a lot of references it can be impossible to track down the broken citation manually, so you have to run the file through pandoc directly and search the output for the error(s).

**Comment by leipert** [comment]
`pandoc exited with code 1: pandoc: [object Object]: openFile: does not exist (No such file or directory)` sounds more like a issue that pandoc doesn't find a file than a citation being faulty.

Could you provide a minimal example that does not work?
Like a really short markdown document and a really short bib file, that crash?
Also your folder structure would be nice, where is the bibtex file in relation to the markdown file.

I can start debugging this on sunday.

@Galadirith We should really add a Debug option to the Settings, so that user can send us logs of the executed pandoc commands and everything :+1:

**Comment by happydemic** [comment]
@leipert 
Turns out the code to display a helpful message was there already, there's just a little bug in it. I think the fix is on line 65 of lib/pandoc-helper.coffee :
`  referenceSearch = /pandoc-citeproc: reference ([\S]+) not found(<br>)?/ig`
should be
`  referenceSearch = /pandoc-citeproc: reference ([\S]+) not found?/ig`

With the fix, MPP displays the pandoc error message(s) identifying unmatched citation(s) as intended.

At some point, maybe a useful enhancement would be for MPP to flag the error and then display the HTML with a placeholder in the text, as pandoc does? There may be other error types where the same principle might apply.
