### ISSUE TITLE
Error message when restarting Atom and restoring the session

### ISSUE THREAD

**Issue by szhorvat** [Galadirith/markdown-preview-plus#129]
Atom can be configures to restore the open files after a restart.  It will also restore any open preview windows.  Those windows will show this message:

![image](https://cloud.githubusercontent.com/assets/1212871/10335036/b86a7598-6cee-11e5-9303-679df383cdaf.png)

This is not a problem for me personally, I just wanted to let you know about it.

Also, in the message "your" should be "your are".

**Comment by Galadirith** [comment]
Thanks @szhorvat, and thanks for catching my terrible spelling.

I believe I actually removed that error message in [71a3513](https://github.com/Galadirith/markdown-preview-plus/commit/71a351392b6f84655e95500a2783cd6d52abe73b#diff-c1dd0615f39950492816a761e2d6d30fL46) so it shouldn't be showing up any longer. Which version of MPP are you running right now? Thanks @szhorvat.

**Comment by szhorvat** [comment]
Oops, I thought I updated to 2.2.0, but I didn't. Something went wrong with the update.  Now I updated and removed `mathjax-wrapper` and that message is indeed gone.  I only get this:

![image](https://cloud.githubusercontent.com/assets/1212871/10335811/ff7271d4-6cf3-11e5-8ff6-62c65d9d259f.png)

**Comment by Galadirith** [comment]
@szhorvat That's great. Those are the notifications you should expect to see when opening a preview on a new load of Atom (but not on every new preview). Glad its working as expected now.

As a note, I added those new notifications because maths doesn't pop in straight away when your opening a preview for the first time and I thought it would be good to provide some user feedback. But if you think those messages are to invasive/distracting/unnecessary please let me know.
