### ISSUE TITLE
Backslash escape not rendered correctly

### ISSUE THREAD

**Issue by gitkrax** [Galadirith/markdown-preview-plus#156]
**Expected behavior:**

`\` escapes following symbols and interprets them literally. Example

`\[arbitrary text\]` renders as `[arbitrary text]`

**Current behavior:**

`\` does not escape when used in conjunction with `[` or `]`.

`\[arbitrary text\]` renders as 

(empty line)
*arbitrary text* (linebreak)

**Note:**

Pandoc still parses the text correctly, it is shown incorrectly only in the Atom preview.

**Versions:**

- Atom 1.2.1
- Markdown Preview Plus 2.2.2.

**Comment by Galadirith** [comment]
@gitkrax Thank you for opening an issue and I really apologise for taking so long to reply.

This is actually the expected behaviour in MPP as the `\[` and `\]` syntax is used to delimit maths blocks which the Pandoc parser doesn't use by default. If you would like to render such a string then you can write
```
\\[arbitrary text\\]
```
which will render as
```
\[arbitrary text\]
```
Alternatively if you don't want to use any of the maths features you can un-tick the `Enable Maths Rendering By Default` in MPP's menu and then it will behave as you expect.

I will now close this issue, but please feel free to post back with any further comments. Thanks again @gitkrax.

**Comment by gitkrax** [comment]
Thanks for clarifying!
