### ISSUE TITLE
Create a stress test document

### ISSUE THREAD

**Issue by szhorvat** [Galadirith/markdown-preview-plus#18]
We should create a stress test document that has all the common constructs that the math preview might conceivably fail on or has failed on in a past release.  This should make it much easier to avoid regressions like #17

**Comment by szhorvat** [comment]
This is just something small I made for myself to hopefully detect problems sooner: https://dl.dropboxusercontent.com/u/38623/math-test.md

**Comment by Galadirith** [comment]
@szhorvat Thank you so much for all the bug reports, its incredibly important so that we can push mpp to stability, so thank you again for your time and effort :D 

The [math-test.md](https://dl.dropboxusercontent.com/u/38623/math-test.md) test document you made looks like a great collection of tests to run, and I will definitely incorporate it.

Most of the bugs you've reported recently stem from my fork of [markdown](https://github.com/Galadirith/markdown/tree/maths-markdown). I will of course comment on each issue individually, but the overall plan is to build some unit test in that fork. But please continue to post issues to [mpp](https://github.com/Galadirith/markdown-preview-plus/issues) as that is the program where your experiencing them :D

Thanks again @szhorvat

**Comment by leipert** [comment]
@szhorvat Thanks for your stress test document. We moved most of your "tests" to real unit tests in 7697921502586256ef4c4f0ea210a08a7c6f17f6

**Comment by szhorvat** [comment]
@leipert  Eagerly waiting for 2.0 :smiley:

**Comment by leipert** [comment]
Well, it will come out on sunday :+1:
