### ISSUE TITLE
[feature request] Indent for markdown Table of Content preview when press "cmd + r"

### ISSUE THREAD

**Issue by gudh** [Galadirith/markdown-preview-plus#181]
Thanks for this amazing plugin! 

Here's my problem:

There is no indent with Atom when I use keyboard **"cmd + r"** to show the Table of Content 

![snip20160211_3](https://cloud.githubusercontent.com/assets/3378031/12972266/aa3eb2e0-d071-11e5-9fa8-ef8a684cfe0d.png)

**While Sublime Text**:

![snip20160211_2](https://cloud.githubusercontent.com/assets/3378031/12972284/c71e9a06-d071-11e5-9eaa-06584aaf0d41.png)

May I ask if it's possible to add indent?

**Comment by Galadirith** [comment]
@gudh Thanks so much for using MPP and I really apologise for taking so long to reply to you.

The `cmd+r` keybinding is actually apart of the [symbols-view ](https://github.com/atom/symbols-view) package and is not something that I would be able to change in MPP directly. 

Its possible that they may be able to change it in their package, however the primary purpose of the `cmd+r` keybinding is not to generate a table of content but to display the list of functions and methods in a file. For the case of a `.md` document it turns out that header are identified as such things.

I'm really sorry I can't give you better news on this issue. I will close this issue now, but please feel free to post back with any comments related to this issue. Thanks again @gudh.
