### ISSUE TITLE
Pipe character within $..$ in markdown table breaks equation across columns

### ISSUE THREAD

**Issue by chrahunt** [Galadirith/markdown-preview-plus#185]
I am trying to create a table that contains LaTeX equations which themselves contain pipe characters, but the pipe characters are evaluated as markdown. Here is a minimal example to reproduce:

```markdown
col a | col b
--|--
$P(A|B)$ | foo
```

results in
![broken table](https://cloud.githubusercontent.com/assets/2312275/13414548/b170e696-df21-11e5-9e8e-22bfd701404f.png)

but the expected result is:
![working table :)](https://cloud.githubusercontent.com/assets/2312275/13414777/337be0ae-df23-11e5-8da8-513a84fd7f7e.png)

If I escape the pipe character then it isn't used as the column delimiter but that impacts the LaTeX rendering:

 ```md
col a | col b
--|--
$P(A\|B)$ | foo
```

results in
![still broken :(](https://cloud.githubusercontent.com/assets/2312275/13414677/66950340-df22-11e5-9fd9-1586462f7467.png)

**Comment by Galadirith** [comment]
@chrahunt Thanks so much for reporting this issue and I really apologise for taking so long to reply to you.

So it looks like bold `**` and italic `*` also suffer from this, except they do escape pipe's correctly. Ticks are treated specially and you can see this in [`table.js`](https://github.com/markdown-it/markdown-it/blob/0e51825a5cd912121d733938ef2603833378888a/lib/rules_block/table.js#L13) in particular on [`table.js#L26-L28`](https://github.com/markdown-it/markdown-it/blob/0e51825a5cd912121d733938ef2603833378888a/lib/rules_block/table.js#L26-L28).

A simple fix would be to simply unescape this in [`markdown-it-helper.coffee#L7`](https://github.com/Galadirith/markdown-preview-plus/blob/d982271e250458f8eef761a2045e349e227b3c78/lib/markdown-it-helper.coffee#L7) but I will have a search around `markdown-it` to potentially make something that is more robust to place in [`markdown-it-maths`](https://github.com/leipert/markdown-it-math).

Thanks again @chrahunt for reporting this, really appreciate it and I will get back to you when i have a candidate fix.

**Comment by Galadirith** [comment]
@chrahunt Thanks again for reporting this.

I have patched [`markdown-it-math`](https://github.com/runarberg/markdown-it-math/compare/runarberg:ec93896...Galadirith:d0e2484) that now correctly supports the pipe character inside inline math. This means it now behaves like inline code, so that you don't have to escape pipe characters for them to not be interpreted as delimiting a column.

The changes in [`markdown-it-math`](https://github.com/runarberg/markdown-it-math/compare/runarberg:ec93896...Galadirith:d0e2484) have been integrated into MPP with 1292e71565f76cfeb3ce38ff6c42f2976ea1d83d and will be published shortly.

 I will close this issue now, but if you still experience any problems related to this problem please feel free to post back to this thread. Thanks again @chrahunt

**Comment by chrahunt** [comment]
Works like a charm, thank you for your effort!

**Comment by Galadirith** [comment]
@chrahunt Brilliant, I'm really glad everything's now working. Please let me know if you have any problem. Thanks again @chrahunt
