### ISSUE TITLE
Tables within quote blocks render outside of quote level

### ISSUE THREAD

**Issue by QnRamoth** [Galadirith/markdown-preview-plus#205]
In Markdown-Preview, placing a table on the next line following a quote block will render the table within the quote block. In Markdown-Preview-Plus, the table always renders at the root indentation, outside of any quote blocks.

For example, if I type:
```
> #### My Table  
>  
Column1 | Column2 | Column3
------- | ------- | -------
ABC     | XYZ     | 123


>> #### My Table
Column1 | Column2 | Column3
------- | ------- | -------
ABC     | XYZ     | 123


> #### My Header
>> #### My Table
>>
Column1 | Column2 | Column3
------- | ------- | -------
ABC     | XYZ     | 123
```

Then I have come to expect the following from Markdown-Preview:
![capture](https://cloud.githubusercontent.com/assets/10822893/14536871/8db33684-0242-11e6-8314-99e8d246c7bd.JPG)

However, I get the following from Markdown-Preview-Plus:
![capture2](https://cloud.githubusercontent.com/assets/10822893/14536884/9c9e6d6c-0242-11e6-8519-abc871caf82e.JPG)

For good measure, here is the result when github renders my original codeblock:
> #### My Table  
>  
Column1 | Column2 | Column3
------- | ------- | -------
ABC     | XYZ     | 123

>> #### My Table
Column1 | Column2 | Column3
------- | ------- | -------
ABC     | XYZ     | 123

> #### My Header
>> #### My Table
>>
Column1 | Column2 | Column3
------- | ------- | -------
ABC     | XYZ     | 123

This would suggest to me that markdown-preview-plus is doing something wrong.

**Comment by Galadirith** [comment]
@QnRamoth Thanks so much for bringing this up.

[`markdown-preview`](https://github.com/atom/markdown-preview) (and I believe GitHub also) use [`marked`](https://github.com/chjj/marked) as there markdown parser, but we use [`markdown-it`](https://github.com/markdown-it/markdown-it). 

While `marked` is great and very feature complete, as far as I am aware it doesn't follow any specific specification for markdown other than John Grubers [original spec](https://daringfireball.net/projects/markdown/) and additions like GitHub markdown tables. `markdown-it` follows the [CommonMark spec](http://spec.commonmark.org/0.25/).

According to the CommonMark spec, tables next to block quotes as you have written in your markdown should not be rendered inside the block quote, and you can read more about that in the [block quote section](http://spec.commonmark.org/0.25/#block-quotes) of the CommonMark spec.

Here is a list of all the tests I could find that `marked` uses for its block quotes and tables

- [`blockquote_list_item.text`](https://github.com/chjj/marked/blob/88ce4df47c4d994dc1b1df1477a21fb893e11ddc/test/new/blockquote_list_item.text)
- [`lazy_blockquotes.text`](https://github.com/chjj/marked/blob/88ce4df47c4d994dc1b1df1477a21fb893e11ddc/test/new/lazy_blockquotes.text)
- [`gfm_tables.text`](https://github.com/chjj/marked/blob/88ce4df47c4d994dc1b1df1477a21fb893e11ddc/test/new/gfm_tables.text)
- [`blockquotes_with_code_blocks.text`](https://github.com/chjj/marked/blob/88ce4df47c4d994dc1b1df1477a21fb893e11ddc/test/tests/blockquotes_with_code_blocks.text)
- [`blockquote_list_item.text`](https://github.com/chjj/marked/blob/88ce4df47c4d994dc1b1df1477a21fb893e11ddc/test/tests/blockquote_list_item.text)
- [`gfm_tables.text`](https://github.com/chjj/marked/blob/88ce4df47c4d994dc1b1df1477a21fb893e11ddc/test/tests/gfm_tables.text)
- [`nested_blockquotes.text`](https://github.com/chjj/marked/blob/88ce4df47c4d994dc1b1df1477a21fb893e11ddc/test/original/nested_blockquotes.text)
- [`blockquotes_with_code_blocks.text`](https://github.com/chjj/marked/blob/88ce4df47c4d994dc1b1df1477a21fb893e11ddc/test/original/blockquotes_with_code_blocks.text)

None of them actually test this specific case that you describe. The fact that it does render the table inside the block quote looks like an unintended consequence of all the other rules, rather than a choice that they have made in the design.

I hope this helps @QnRamoth. This is not something that I would plan to change in `markdown-preview-plus` but if you have any other questions of comments please feel free to post back to this issue. Thanks again.
