### ISSUE TITLE
just a ping from the MathJax team

### ISSUE THREAD

**Issue by pkra** [Galadirith/markdown-preview-plus#21]
Hi @Galadirith. @szhorvat pinged us about your awesome project -- congrats! It looks very solid already.  

Do let us know if we can help with any questions about MathJax, MathJax-node etc. either via GitHub, or by chat/mail/etc.

**Comment by Galadirith** [comment]
Hi @pkra. Thank you so much for the message of support, im quite taken aback that [markdown-preview-plus](https://github.com/Galadirith/markdown-preview-plus) is even on your radar, but it means a tremendous amount.

As we move the project forward its really great to know there's a place to ask questions. Thanks again @pkra (and the new [MathJax](http://www.mathjax.org/) is looking fantastic)

**Comment by pkra** [comment]
Thanks for your kind words. 

It's only tangential but it looks like the mathjax-wrapper installs an almost full copy of MathJax. A stripped down version could be as low as 1.5MB depending on your preferences. Most of the bugs seem to be due to the trouble of isolating TeX from markdown. Have you looked at the tex2jax pre-processor? Depending on how your markdown parser handles HTML, it migh be easier to use approach where MathJax or at least the pre-processor runs first.

**Comment by Galadirith** [comment]
@pkra thanks so much for your thoughts.

Originally I was using mathjax-node but I couldn't [configure the svg output](http://docs.mathjax.org/en/latest/options/SVG.html) to render nearly as well in Atom as the HTML/CSS output (unlike in browsers where they are quite close). mathjax-node pulls down my [really naive attempt](https://github.com/Galadirith/MathJax/tree/mathjax-complete-node) at wrapping a full copy of MathJax as a node package without any wrapping API. I didn't consider stripping any files as I wasn't sure which once were necessary for HTML/CSS output. If that is something you would prefer I didn't do please let me know as the last thing I want to be doing is infringing on any of your work.

I haven't tried using mathjax-node for several months though, certainly not since `v2.5` and Atom has moved on a lot since then, so I will definitely revisit it.

I was also using the tex2jax pre-processor at the beginning of development, but I ran into problems with lexing other markdown blocks. For example `$$` delimiters inside a code block delimited by ```` ``` ```` should not be identified as a displayed maths block but by running the tex2jax preprocessor first they would be. Most of the issues that pop up right now are related to edge cases I didn't considered when I laid down my [regex](https://github.com/Galadirith/marked/blob/991b9beab5453ab4366f3f2881a365f0cfd816a0/lib/marked.js#L78) but thanks awsome people like @szhorvat and @KCErb its getting better.

**Comment by pkra** [comment]
> I couldn't configure the svg output to render nearly as well in Atom as the HTML/CSS output

What kind of issues did you encounter? Would be interesting to see if we can do something about them.

> I didn't consider stripping any files as I wasn't sure which once were necessary for HTML/CSS output.

Check out https://github.com/mathjax/MathJax-grunt-cleaner.

>  If that is something you would prefer I didn't do please let me know as the last thing I want to be doing is infringing on any of your work.

MathJax source is Apache licensed so you can manipulate it accordingly :-)

> For example $$ delimiters inside a code block delimited by ``` should not be identified as a displayed maths block but by running the tex2jax preprocessor first they would be. 

Ah, interesting. Perhaps a markdown-compatibility extension for MathJax is worth considering.

**Comment by pkra** [comment]
> I couldn't configure the svg output to render nearly as well in Atom as the HTML/CSS output

What kind of issues did you encounter? Would be interesting to see if we can do something about them.

> I didn't consider stripping any files as I wasn't sure which once were necessary for HTML/CSS output.

Check out https://github.com/mathjax/MathJax-grunt-cleaner.

>  If that is something you would prefer I didn't do please let me know as the last thing I want to be doing is infringing on any of your work.

MathJax source is Apache licensed so you can manipulate it accordingly :-)

> For example $$ delimiters inside a code block delimited by ``` should not be identified as a displayed maths block but by running the tex2jax preprocessor first they would be. 

Ah, interesting. Perhaps an extension of the pre-processor makes sense here. Anyway, glad to hear you a regex solution working.

**Comment by KCErb** [comment]
+1 for github-flavored markdown compatible MathJax!

**Comment by Galadirith** [comment]
> What kind of issues did you encounter? Would be interesting to see if we can do something about them.

![svg-vs-htmlcss](https://cloud.githubusercontent.com/assets/1201875/6071621/dcd0b484-ad8f-11e4-9de7-23519126e24e.png)

These are screen shots of HTML-CSS vs SVG output in Atom and I think I have made something out of nothing here.

Looking at this I think *'couldn't configure the svg output to render nearly as well'* was an overstatement by me. I would guess that the extra sharpness in the HTML-CSS output is because of font hinting? *'unlike in browsers where they are quite close'* is also not true, that difference between outputs is present in browsers, I should have been more thoughtful when I originally tested the outputs. 

I would certainly imagine this has nothing to do with MathJax, as the physical layout of the SVG is perfect.

> Check out https://github.com/mathjax/MathJax-grunt-cleaner.

Thats fantastic, the perfect tool :D

**Comment by pkra** [comment]
Ah, ok. Try configuring the SVG output to `blacker: 1` (see http://docs.mathjax.org/en/latest/options/SVG.html). We're revisiting this soon https://github.com/mathjax/MathJax/issues/994. (The reason the stroke width is set so high is that back in the day some SVG engines were so unstable that lower values would make paths disappear; this seems to have improved on the browser side and definitely isn't a problem when you just have one engine to worry about).

**Comment by Galadirith** [comment]
@pkra thanks so much for the suggestion, and I'm really sorry I wasn't able to respond sooner.
![svg-vs-htmlcss](https://cloud.githubusercontent.com/assets/1201875/6139804/e2adb572-b187-11e4-925d-ce53bf1ee058.png)
`blacker: 1` definitely looks much closer to `HTML/CSS` output, and so far I haven't seen any paths vanishing which is great. There are subtle aliasing problems that are particularly noticeable with horizontal or vertical lines for example in the `-` and `+` in the `SVG BLACKER 1` output that look not as sharp as the `HTML/CSS`.

I do think for right now `HTML/CSS` output is still the best choice in Atom, but with every new version I'll make sure to continue to test `SVG` output as chrome evolves :D

**Comment by pkra** [comment]
>  There are subtle aliasing problems that are particularly noticeable with horizontal or vertical lines for example

Yes, the trouble is that SVG does not get sub-pixel but only b/w anti-aliasing.
