### ISSUE TITLE
Preview won't open on MBP with Atom 0.188

### ISSUE THREAD

**Issue by TheVaan** [Galadirith/markdown-preview-plus#30]
Hi!

Installation of MD Preview Plus and mathjax-wrapper has been successful. I also disabled the build in markdown preview.
But pressing ^ + ⇧ + M doesn't show the preview window... There are no warnings / errors in the log. I also uninstalled and reinstalled the package.
Did I forgot anything?

By the way: Building the tex file with an other LaTeX package works fine.

Hope you can help me...

**Comment by Galadirith** [comment]
@TheVaan I incredibly sorry for not having been able to get back to you sooner on this.

Have you had any success since you opened the issue? I have just pushed out a new version of MPP that may cure your problem so you could try updating to that.

Also have you tried opening a preview window through the menu option **Packages &rsaquo;
Markdown Preview Plus &rsaquo; Toggle LaTex Rendering**.

Please let me know how everything goes :D

**Comment by TheVaan** [comment]
@Galadirith because of your changes of the readme.md I realized, that there was never a support for showing latex files - my bad, I didn't noticed that before. Sorry! But thank you anyway for your answer!

**Comment by Galadirith** [comment]
@TheVaan Oh I am so sorry about its was never my intention to mislead people into thinking MPP could render LaTeX files. Thanks for the reply :D
