### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by veltall** [Galadirith/markdown-preview-plus#34]
## Request
I've been using the [`markdown-pdf`](https://github.com/travs/markdown-pdf) package in Atom to export to PDF, but the plugin requires the built-in `markdown-preview` as a dependency. As a result, the exporter does not work with **Markdown Preview Plus**.

It would be great if MPP could provide an export option in a single dependency package. Though I understand that MPP perhaps should not be incorporating all the functionalities from all the plugins which have dependency on the standard `markdown-preview` package that it replaces. Therefore, I'd appreciate any guidance helping me hack my way through this problem.

## Details
`markdown-pdf` pre-pends the CSS from the [`markdown-preview` atom package](https://github.com/atom/markdown-preview) to the HTML provided by [`marked`](https://www.npmjs.org/package/marked).

If said CSS is also available in MPP (which I suspect it should be), then it ought to be possible to modify `markdown-pdf` to work with MPP instead of `markdown-preview`.

**Comment by Galadirith** [comment]
@veltall Im terribly sorry for not having been able to respond to you sooner, I would most definitely love to help you out with this enhancement.

As far as incorporating a pdf export option into MPP I actually personally think it would be a great addition, and something I keep wanting myself. In fact from a user perspective I think it makes more sense to incorporate it into MPP rather than fork `markdown-pdf`. So yes I would definitely be up for that but I'm not going to have time to do this myself before June 15th, i'm really sorry about that.

So guidance on the hack until I can incorporate the export. Well it looks like the only places that reference `markdown-preview` directly are at line [L5](https://github.com/travs/markdown-pdf/blob/3883d651eabcb499cd89771c2889d525b80cb437/lib/markdown-pdf.js#L5), [L62](https://github.com/travs/markdown-pdf/blob/3883d651eabcb499cd89771c2889d525b80cb437/lib/markdown-pdf.js#L62) and [L106](https://github.com/travs/markdown-pdf/blob/3883d651eabcb499cd89771c2889d525b80cb437/lib/markdown-pdf.js#L106). You also want to follow the `mdpreview` variable that is defined on L5.

I would start with substituting the occurrences of `markdown-preview` on L5, L62 and L106 for `markdown-preview-plus`. All of the methods from `markdown-preview` that `markdown-pdf` calls also exist in `markdown-preview-plus` so you might get lucky and that'll be enough.

But Realistically it will probably be a little more complicated then just that :D But start there.

Let me know how it goes. Please ask me any question you have and I'll do my best to get back to you :D

**Comment by leipert** [comment]
@Galadirith Candidate for 2.0.0 or do we create a PR in markdown-pdf ?

**Comment by Galadirith** [comment]
@leipert For now I think a PR would be best; wherever possible I would prefer modularity over one monolithic package doing everything. Plus `markdown-pdf` depends on `phantomjs` which could add a reasonably large download for user's who don't already have it installed globally on their system.

The big problem is making sure that the math's is rendered properly. Right now [`copyHtml()`](https://github.com/Galadirith/markdown-preview-plus/blob/88100d6c2a1b7fcbc681bee0b9ecd7d03979860e/lib/main.coffee#L195) (which is how `markdown-pdf` grabs the converted markdown) doesn't output the MathJax converted equations because it is not designed to copy styles as well, just html snippets. Without the font's from the styles added by MathJax its not going to look like anything good. 

What I believe would be a viable solution is to switch the MathJax renderer to svg only for the duration of the copy operation, render the equations as svg's and send that to `markdown-pdf`.

The other option would be to have `copyHtml()` borrow behaviour from [`saveAs()`](https://github.com/Galadirith/markdown-preview-plus/blob/88100d6c2a1b7fcbc681bee0b9ecd7d03979860e/lib/markdown-preview-view.coffee#L297), maybe just refactor the code so that its a method on the main module rather than requiring a preview window to be open. This creates a HTML document that loads MathJax from the CDN rather than locally. I've just tested running a HTML document saved by MPP in [`pageres-cli`](https://github.com/sindresorhus/pageres-cli) which uses `phantomjs` and it seems to handle it fine, with caveats that equations seem to be rendered smaller than usual which can be handled in MathJax's configuration, and MathJax of course takes time to process the page but I think `markdown-pdf` could handle that with [timeout](https://github.com/travs/markdown-pdf/blob/b8c92ef43cc786f17e6a1371facbd038ad0f4c60/lib/markdown-pdf.js#L22)

What do you think of the two solutions? The first is untested but would be an almost transparent PR for `markdown-pdf`, the second is partially successfully tested, but it wouldn't be as small a PR (although it still would be reasonably small :D)

**Comment by leipert** [comment]
I think the best solution would be to maintain as much compatibility with markdown-preview as possible, so `copyHTML()` should just work for any other package that want's to use it.

Furthermore I don't know if I would prefer the first or second solution. The svg solution also means a higher compability, as it works even if javascript is disabled.

Maybe we can give a setting which let's you choose between SVG and Javascript on HTML Export.

 I just thought if the user has pandoc enabled we could give him an export to pdf with pandoc option :)

**Comment by Galadirith** [comment]
> I think the best solution would be to maintain as much compatibility with markdown-preview as possible

I agree :D In which case I will run with the svg solution for now and will spin upgrading `copyHtml()` out into its own issue.

> I just thought if the user has pandoc enabled we could give him an export to pdf with pandoc option :)

That sounds pretty awesome. You would of course no best about how complicated that would be to implement, but I'm guessing not very? just calling pandoc with a few different options?

**Comment by leipert** [comment]
Closed in favor of #55, #56 and #57

**Comment by Galadirith** [comment]
@veltall I just wanted to send you an update on this issue. We will hopefully be adding support for exporting to PDF with our `2.2.0` release in a couple of weeks time. I really appreciate your patience on this and I'm sorry that its taken so long to implemented it. Thanks again @veltall :D

**Comment by veltall** [comment]
Lovely! I'm sorry for not having followed the issue at all because I stepped away from Atom for various reasons.
