### ISSUE TITLE
unable to save as html

### ISSUE THREAD

**Issue by zhnuaa** [Galadirith/markdown-preview-plus#38]
it's ok to preview,but unable to save as html.
it export nothing when i try to save the result, neither under windows nor linux.
any help?

**Comment by Galadirith** [comment]
@zhnuaa Thanks so much for raising the issue and I'm very sorry its taken me so long to get back to you. This feature is currently not working correctly in MPP but I will hopefully have a fix for this published by Sunday. Thanks again @zhnuaa I will update you when the fix is published.

**Comment by naubry** [comment]
Have you any news about this update in order to fix this issue ?
And news about a feature like save to pdf file :D ?

**Comment by zhnuaa** [comment]
no update news. i tried the new version after the developer replied. but the issue is still there. actually i'm now using haroopad instead and waiting for the issue fixed. 发自网易邮箱大师 On 2015-07-08 23:16 , AUBRY Nicolas Wrote: Have you any news about this update in order to fix this issue ? And news about a feature like save to pdf file :D ? — Reply to this email directly or view it on GitHub.

**Comment by Galadirith** [comment]
Hey @zhnuaa @naubry. Im so sorry its taken me so long to fix this. I've just published a new version [`1.6.0`](https://github.com/Galadirith/markdown-preview-plus/releases/tag/v1.6.0) a few minutes ago  that fixes save as HTML.

> And news about a feature like save to pdf file :D?

@naubry I didn't have any immediate plans to add this feature but I know that's an important feature for a lot of people. I had a conversation with @veltall a while ago [here](https://github.com/Galadirith/markdown-preview-plus/issues/34#issuecomment-99641249) about how you could modify [`markdown-pdf`](https://github.com/travs/markdown-pdf) to do just this. While I can't promise I'd be able to publish anything or send a pr to markdown-pdf I'd be happy to walk you through the modifications that would be needed on your local installation of markdown-pdf. If you'd like to do that just add a comment to Galadirith/markdown-preview-plus#34 so that we can merge the conversation on that feature :D 

I hope that helps :D. Once again I'm really sorry again for the long wait and please post back if you have any problems.

**Comment by leipert** [comment]
@Galadirith Is this fixed?

**Comment by zhnuaa** [comment]
yes, the issue has been fixed.
