### ISSUE TITLE
Installing v1.4.0 on Mac OS X gives error

### ISSUE THREAD

**Issue by aadm** [Galadirith/markdown-preview-plus#39]
Ok so I was unable to update v1.3 to 1.4 on my system (Mac OS X v10.10.3 running macbook pro 13" retina late 2014). I uninstalled it then tried to install it back again but no luck.

Atom version is 0.204.0; I followed all the installation instruction provided (only I couldnt understand really what's node-gyp but since you wrote it's installed by default with atom I think it's ok?...).

This is the error msg:

```
Installing “markdown-preview-plus@1.4.0” failed.Hide output…

npm ERR! fetch failed https://atom.io/download/atom-shell/nan-1.6.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://atom.io/download/atom-shell/nan-1.6.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 401
npm ERR! fetch failed https://atom.io/download/atom-shell/nan-1.6.1.tgz
npm ERR! Darwin 14.3.0
npm ERR! argv "/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/bin/node" "/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/aadm/.atom/.apm/.apmrc" "--userconfig" "/Users/aadm/.atom/.apmrc" "install" "/private/var/folders/0j/2b0lk_wj20vgm0bdd_85zlsh0000gn/T/d-115429-24786-d2i9wa/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1

npm ERR! fetch failed with status code 401
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/0j/2b0lk_wj20vgm0bdd_85zlsh0000gn/T/apm-install-dir-115429-24786-35lzxa/npm-debug.log
```

Oh and that file that I'm supposed to include with support request (` /private/var/folders/0j/2b0lk_wj20vgm0bdd_85zlsh0000gn/T/apm-install-dir-115429-24786-35lzxa/npm-debug.log`)? I couldnt find it.

Hope somebody can help me out and thanks in advance!

Alessandro

**Comment by Galadirith** [comment]
@aadm I very sorry for not having been able to get back to you soon on this. 

Have you been able to install MPP since you opened the issue? From the error information it looks like your behind a proxy server. If your still running into problems I would be grateful if you could try installing MPP with a verbose output. You can do that by running

````bash
$ apm install markdown-preview-plus --verbose
````

and post the output to this issue. 

It looks like `apm` doesn't seem to like the direct link to the node package `nan` (one example is [L44](https://github.com/atom/node-pathwatcher/blob/1b5e1c6dacecd8d08e874c18e73e94dc6620b814/package.json#L43) of pathwatcher). There also seems to be a more widespread problem with installing packages behind proxies atom/apm#322.

Let me know how the install attempt goes and hopefully we can get you up an running with MPP very soon.

**Comment by aadm** [comment]
Hi and thanks for the reply. I have recently upgraded atom to 1.0 and then I had no problem in updating MPP to 1.5.0.

Thanks again -- really great work this MPP!

**Comment by Galadirith** [comment]
@aadm Im really glad everything is now working. Thanks and let me know if your have any more problems in the future :D
