### ISSUE TITLE
context menu option doesn't show in tree view on 1.7

### ISSUE THREAD

**Issue by SlimeQ** [Galadirith/markdown-preview-plus#76]
i've recently upgraded to atom 1.7 and the markdown option that used to be in the tree view context menu is gone. rendering still works fine via the packages menu

**Comment by Galadirith** [comment]
Thanks @SlimeQ for catching this issue. That is odd, something has changed in the latest release of Atom. We'll make sure its fixed for the next release :D

**Comment by Galadirith** [comment]
@SlimeQ After some investigation it would seem that the problem is with atom/tree-view. I've opened an issue atom/tree-view#555 over there. Hopefully those guys will be able to roll out a fix soon but if you wanted me to I'd be happy to give you some steps to install your own patched version of `tree-view` that brings back the context menu option until a stable solution is found by the tree-view team.

**Comment by Galadirith** [comment]
@SlimeQ As of Atom `v1.0.9` this should now be fixed by https://github.com/atom/atom/commit/ae238b02f683cf7be45d712c6f85aab6ced53c8d. I'll close the issue but please let us know if you encounter any problems in the future.
