### ISSUE TITLE
Equation Numbers?

### ISSUE THREAD

**Issue by KCErb** [Galadirith/markdown-preview-plus#8]
Howdy again,

Loving this tool! Thank you!

I'm struggling to get my equations to autonumber. Based on a little bit of reading around it looks like using 

```
$$ y = mx+b $$
```
 is equivalent to 
```
\begin{equation}
y = mx+b
\end{equation}
```

which should autonumber in LATEX.

Also in MathJax we get autonumbering with [a config setting](http://docs.mathjax.org/en/latest/tex.html#automatic-equation-numbering).

I tried adding this setting to my copy of the package (and was considering attempting a pull request since I've never built / contributed to an Atom package) by changing

```coffee
configureMathJax = ->
  MathJax.Hub.Config
    jax: ["input/TeX","output/HTML-CSS"]
    extensions: []
    TeX:
      extensions: ["AMSmath.js","AMSsymbols.js","noErrors.js","noUndefined.js"]
    messageStyle: "none"
    showMathMenu: false
  MathJax.Hub.Configured()
  return
```

to

```coffee
configureMathJax = ->
  MathJax.Hub.Config
    jax: ["input/TeX","output/HTML-CSS"]
    extensions: []
    TeX:
      extensions: ["AMSmath.js","AMSsymbols.js","noErrors.js","noUndefined.js"]
      equationNumbers: { autoNumber: "AMS" }
    messageStyle: "none"
    showMathMenu: false
  MathJax.Hub.Configured()
  return
```

But I'm still not getting numbers. 
Thoughts?

**Comment by KCErb** [comment]
Hi again, thought I'd just give you an update. I got busy at the end of last semester and basically forgot all about this :blush: but now I'm taking a course and am going to attempt to take all of my notes in markdown via this package! :grin: 

I may have time to circle back to this but for now I'll just throw in my 2 cents:

I don't actually think it's a problem for the numbers to be out of order. What I mean is that the case where I would want to really be able to use an equation number would be when I'm going back and reviewing my notes, i.e. looking back on a more-or-less finished product. 

So to me, if during the execution stage I mess up equation ordering that's a not a big deal. But I understand why you still might hesitate to include a feature like this until the bug gets resolved. It'd be great if I could dig in and get something working but I'll not promise anything :)

Thanks again for the great package, for the first time in my life I have notes that I can read from a physics class!

**Comment by Galadirith** [comment]
@KCErb Absolutely no problem at all. I'm sorry too that I haven't been able to implelement this. I completely empathise with you, i've got university work too and it kills me to not have the time to work on this package more :D 

So for now I think I have some code you can add to your installation that should do exactly what your describing. If you open up `~/.atom/packages/markdown-preview-plus/lib/mathjax-helper.coffe` and make the following modifications:

````javascript
  mathProcessor: (domElements) ->
    if MathJax?
      MathJax.Hub.Queue ["Typeset", MathJax.Hub, domElements]
    return
````
&rarr;
````javascript
  mathProcessor: (domElements) ->
    if MathJax?
      try
        MathJax.Extension["TeX/AMSmath"].startNumber = 0
      catch
      MathJax.Hub.Queue ["Typeset", MathJax.Hub, domElements]
    return
````

and the following

````javascript
configureMathJax = ->
  MathJax.Hub.Config
    jax: ["input/TeX","output/HTML-CSS"]
    extensions: []
    TeX:
      extensions: ["AMSmath.js","AMSsymbols.js","noErrors.js","noUndefined.js"]
    messageStyle: "none"
    showMathMenu: false
  MathJax.Hub.Configured()
  return
````
&rarr;
````javascript
configureMathJax = ->
  MathJax.Hub.Config
    jax: ["input/TeX","output/HTML-CSS"]
    extensions: []
    TeX:
      extensions: ["AMSmath.js","AMSsymbols.js","noErrors.js","noUndefined.js"]
      equationNumbers:
        autoNumber: "all"
    messageStyle: "none"
    showMathMenu: false
  MathJax.Hub.Configured()
  return
````

This numbers all displayed equation. You can manually tag individual equations to not be numbered or change `autoNumber: "all"` to `autoNumber: "AMS"`. you can find more details at [Automatic Equation Numbering](http://docs.mathjax.org/en/latest/tex.html#automatic-equation-numbering).

The `MathJax.Extension["TeX/AMSmath"].startNumber = 0;` means after the initial typset off all the equations in the document, and subsequent modifications will be numbered with `(1)`. I thought that would be best instead of letting the numbers climb up arbitrarily high; not only would it be annoying to have a really big number there (i think :D), it would also change to a new number with every modification, no matter how small, which I think would be distracting. This way it will always remain at `(1)` after the initial typeset and so visually appear never to change.

If your equation numbers have got a little to funky at any point, it should just be enough to close and re-open the preview tab (you shouldn't have to reload atom) to have your equations numbered in the correct order.

Do let me know if you have any problems with that :D I really hope you have fun on your course :D

**Comment by KCErb** [comment]
Thanks again friends. Works well (for) now, I'll post back here with other thoughts and comments on equation numbering as time goes on.
